import {useRef,useState} from 'react';
import {Button,Field} from './components';
import {fleet} from './live-api';
export function AgentLifecycle({id,action,done}:{id:string;action:'restart_resume'|'restart_fresh';done:()=>Promise<void>}) {
 const storageKey='fleet-pending-lifecycle:'+id;const saved=useRef<{actionId:string;action:string}|null>(JSON.parse(sessionStorage.getItem(storageKey)||'null'));const key=useRef(saved.current?.actionId??crypto.randomUUID());const [confirmed,setConfirmed]=useState('');const [started,setStarted]=useState(!!saved.current);const [busy,setBusy]=useState(false);const [status,setStatus]=useState('');const [error,setError]=useState('');
 const fresh=action==='restart_fresh';
 const check=async()=>{setBusy(true);setError('');try{for(let i=0;i<30;i++){const receipt=await fleet(`/actions/${encodeURIComponent(key.current)}`);setStatus(receipt.state);if(receipt.state==='succeeded'){sessionStorage.removeItem(storageKey);await done();return;}if(receipt.state==='failed')sessionStorage.removeItem(storageKey);if(['failed','uncertain'].includes(receipt.state))throw Error(receipt.error?.message??'The restart result is uncertain. Inspect the agent before another action.');await new Promise(r=>setTimeout(r,1000));}setStatus('Still pending. Check status to continue observing this action.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 return <>{saved.current&&<p>A previous {saved.current.action==='restart_fresh'?'force restart':'restart'} is awaiting confirmation. Check its status before starting another.</p>}<p>{fresh?'Start a fresh session. The current conversation context will be cleared.':'Restart the agent and resume its saved session.'}</p><p>The saved agent configuration will be applied.</p>{fresh&&<Field label={`Confirm agent ID: ${id}`}><input value={confirmed} disabled={started} onChange={e=>setConfirmed(e.target.value)}/></Field>}{status&&<p role="status">{status}</p>}{error&&<p role="alert">{error}</p>}{!started?<Button disabled={busy||(fresh&&confirmed!==id)} onClick={async()=>{setStarted(true);setBusy(true);setError('');try{sessionStorage.setItem(storageKey,JSON.stringify({actionId:key.current,action}));await fleet(`/roles/${encodeURIComponent(id)}/actions`,{action,actionId:key.current,...(fresh?{confirmation:confirmed}:{})});await check();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}>{fresh?'Force restart':'Restart'}</Button>:<Button disabled={busy} onClick={()=>void check()}>Check restart status</Button>}</>;
}
