import { useState } from 'react';
import { Bot, Brain, UserRound, Lock, SlidersHorizontal } from 'lucide-react';
import DialogShell from '../ui/DialogShell';
import { Button, Field } from './components';
import { effortChoices } from './configuration';
import { useConfiguration } from './Configuration';
import { FolderPicker } from './FolderPicker';
export interface DraftAgent { id: string; name: string; role: string; brain: string; permissions: string; folder: string; unattended?: string; effort?: string }
export function ChatSetup({ draft, onChange, locked = false }: { draft: DraftAgent; onChange?: (next: DraftAgent) => void; locked?: boolean }) {
  const config=useConfiguration();
  const [options, setOptions] = useState(false);
  const [folder, setFolder] = useState(false);
  const change = (key: keyof DraftAgent, value: string) => { if(!locked) onChange?.({ ...draft, [key]: value, ...(key==='brain'?{effort:undefined}:{}) }); };
  const fields = <div className="fleet-setup-fields"><label><Bot size={19} /><span>Name<input aria-label="Agent name" value={draft.name} onChange={e => change('name', e.target.value)} /></span></label><label><UserRound size={19} /><span>Role<select aria-label="Role" value={draft.role} onChange={e => change('role', e.target.value)}>{Object.keys(config.data.role).map(x => <option key={x}>{x}</option>)}</select></span></label><label><Brain size={19} /><span>Brain<select aria-label="Brain" value={draft.brain} onChange={e => change('brain', e.target.value)}>{Object.entries(config.data.brain).map(([id,b])=><option key={id} value={id}>{b.harness} · {b.model ?? 'Default model'} · {b.effort ?? 'Default effort'}</option>)}</select></span></label><label><SlidersHorizontal size={19}/><span>Effort<select aria-label="Effort" value={draft.effort ?? config.data.brain[draft.brain]?.effort ?? ''} onChange={e=>change('effort',e.target.value)}><option value="">Default effort</option>{effortChoices(config.data.brain[draft.brain]?.harness,config.data.brain[draft.brain]?.model).map(e=><option key={e}>{e}</option>)}</select></span></label><label><Lock size={19}/><span>Permissions<select aria-label="Permissions" value={draft.permissions} onChange={e=>change('permissions',e.target.value)}><option>Ask before changes</option><option>Read only</option><option>Workspace edits</option><option>Allow · Full access</option></select></span></label></div>;
  if(locked) return <details className="fleet-locked-setup"><summary><Lock size={14} /> Session settings · Locked</summary><dl>{[['Name', draft.name], ['Role', draft.role], ['Brain', `${config.data.brain[draft.brain]?.harness ?? ''} · ${config.data.brain[draft.brain]?.model ?? 'Default model'} · ${draft.effort ?? config.data.brain[draft.brain]?.effort ?? 'Default effort'}`], ['Folder', draft.folder], ['Permissions', draft.permissions]].map(([label, value]) => <div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl></details>;
  return <section className="fleet-chat-setup" aria-label="New chat settings"><h2>New chat</h2><p>Send a message to start your agent.</p>{!options && fields}<Button onClick={() => setOptions(true)}><SlidersHorizontal size={16} /> More options</Button><small>Settings lock after your first message.</small>
    {options && <DialogShell title={folder ? 'Choose folder' : 'Make it yours'} className="fleet-modal" onClose={() => folder ? setFolder(false) : setOptions(false)}>{folder && config.live ? <div className="fleet-dialog-content"><Field label="Working folder"><input value={draft.folder} placeholder="Fleet default" onChange={e=>change('folder',e.target.value)}/></Field><p>Use an existing folder on this host, or leave blank for the Fleet default.</p><Button onClick={()=>setFolder(false)}>Done</Button></div> : folder ? <FolderPicker value={draft.folder} onCancel={() => setFolder(false)} onSelect={value => { change('folder', value); setFolder(false); }} /> : <div className="fleet-dialog-content">{fields}<Button onClick={() => setFolder(true)}>Folder · {draft.folder.split('/').pop() || 'Fleet default'}</Button><Button primary onClick={() => setOptions(false)}>Done</Button></div>}</DialogShell>}
  </section>;
}
