import { useState } from 'react';
import { Onboarding } from './Onboarding';
import { Button, Field, PageHeader, Row, SearchField } from './components';
import type { Agent, Modal, Page, Section } from './model';
export function ProfilePage({ page, agents, go, back, openChat, openRoom, modal }: { page: Extract<Page, {kind: 'profile' | 'contacts'}>; agents: Agent[]; go: (p: Page) => void; back: () => void; openChat: (id: string, section?: Section) => void; openRoom: (id: string) => void; modal: (m: Modal) => void }) {
  const [search, setSearch] = useState('');
  const a = agents.find(a => a.id === page.id || `messenger-${a.id}` === page.id);
  // Messenger history IDs are presentation routes, never invitation actors.
  const id = a?.id ?? page.id;
  const human = id === 'human' || id === 'mira'; const workspace = id === 'workspace' || id === 'personal' || id === 'mira-workspace';
  const foreign = id === 'alex-reviewer' || id === 'external-developer' || id === 'mira' || id === 'mira-workspace';
  const person = id === 'maya' || id === 'noor';
  const name = a?.name ?? ({ human: 'Vitalii Shakhmatov', workspace: 'Vitalii · Work', personal: 'Vitalii · Personal', mira: 'Mira Chen', 'mira-workspace': 'Mira · Work', 'alex-reviewer': 'Alex’s reviewer', 'messenger-developer': 'Developer', maya: 'Maya', noor: 'Noor' }[id] ?? 'Agent');
  const visit = (id: string) => go({ kind: 'profile', id });
  return <main className="fleet-page"><Button onClick={back}>‹ Back</Button><section className="fleet-profile">
    {page.kind === 'contacts' ? <><PageHeader title="Agent contacts" subtitle={`Acting as ${name} · Vitalii · Work`} onBack={() => visit(id)} /><SearchField value={search} onChange={setSearch} placeholder="Search contacts" />{agents.filter(x => x.id !== id && x.name.toLowerCase().includes(search.toLowerCase())).map(x => <Row key={x.id} title={x.name} subtitle="Agent" onClick={() => visit(x.id)} />)}<Row title="Launch website · Room" subtitle="Shared room" onClick={() => openRoom('0mu1gv4ndd96af6f4')} /><div className="fleet-actions"><Button primary onClick={() => modal({ kind: 'generate', actor: id, locked: true })}>Generate invite</Button><Button onClick={() => modal({ kind: 'accept', actor: id, locked: true })}>Accept invite</Button></div></> : <><div className="fleet-profile-avatar">{name.split(' ').map(x => x[0]).join('').slice(0, 2)}</div><h1>{name}</h1><p>{human || person ? 'Human identity' : workspace ? 'Workspace identity' : a ? `Your agent · ${a.state}` : 'Agent · Contact'}</p><p>{human ? 'Building tools for people and their agents.' : !workspace && !person ? 'Builds and reviews the website with your task team.' : ''}</p>{!human && !person && <small className="muted">{workspace ? 'Workspace' : 'Identity'} · {foreign ? 'C6B9…204E' : '8A42…71C9'}</small>}
    {human && <><h2>Workspace identities</h2><Row title={foreign ? 'Mira · Work' : 'Vitalii · Work'} subtitle="Workspace identity" onClick={() => visit(foreign ? 'mira-workspace' : 'workspace')} />{!foreign && <Row title="Vitalii · Personal" subtitle="Workspace identity" onClick={() => visit('personal')} />}</>}
    {workspace && <><Row title={foreign ? 'Mira Chen' : 'Vitalii Shakhmatov'} subtitle="Human identity" onClick={() => visit(foreign ? 'mira' : 'human')} /><h2>Known agents</h2>{(foreign ? [{ id: 'external-developer', name: 'Developer' }] : agents).map(x => <Row key={x.id} title={x.name} subtitle="Agent" onClick={() => visit(x.id)} />)}{!foreign && <Row title="Alex’s reviewer" subtitle="Agent · Contact" onClick={() => visit('alex-reviewer')} />}</>}
    {!human && !workspace && !person && <><Row title={foreign ? 'Mira · Work' : 'Vitalii · Work'} subtitle="Workspace identity" onClick={() => visit(foreign ? 'mira-workspace' : 'workspace')} /><Row title={foreign ? 'Mira Chen' : 'Vitalii Shakhmatov'} subtitle="Human identity" onClick={() => visit(foreign ? 'mira' : 'human')} /><Button primary onClick={() => openChat(a?.id ?? id, a ? 'work' : 'messenger')}>{a ? 'Open agent chat' : 'Message agent'}</Button>{a && <Button onClick={() => go({ kind: 'contacts', id })}>Contacts & invitations</Button>}</>}
    {person && <Button primary onClick={() => openChat(id, 'messenger')}>Message {name}</Button>}
    {id === 'human' && <div className="fleet-profile-links"><Button onClick={() => go({ kind: 'account', step: 'login' })}>Account</Button><Button onClick={() => go({ kind: 'empty' })}>Getting started</Button></div>}
    </>}
  </section></main>;
}
const definitions: Record<string, { title: string; intro: string; fields: [string, string][] }> = {
  template: { title: 'Developer template', intro: 'A reusable starting point for new sessions.', fields: [['Template name', 'Developer'], ['Role', 'Developer'], ['Brain', 'Codex'], ['Permission profile', 'Workspace edits'], ['Default folder', '/home/you/work']] },
  role: { title: 'Developer role', intro: 'Define the job; keep runtime choices in Brains.', fields: [['Role name', 'Developer'], ['Purpose', 'Implement the assigned task and provide verification evidence'], ['Instructions', 'Stay in scope. Report material failures. Preserve unrelated work.'], ['Context / briefing', 'Applied at creation and when joining a task room']] },
  brain: { title: 'Codex brain', intro: 'Choose the runtime used by agent templates.', fields: [['Brain name', 'Codex'], ['Harness', 'Codex'], ['Model', 'Use configured default'], ['Runtime options', 'Default reasoning'], ['Credentials', 'Configured on Workstation · Secret masked']] },
  permissions: { title: 'Workspace edits', intro: 'A reusable boundary for an agent’s operations.', fields: [['Profile name', 'Workspace edits'], ['Files', 'Read and write within the selected working folder'], ['Commands', 'Ask for approval according to host policy'], ['Network', 'Host-supported controls only'], ['Outside the workspace', 'No implicit access']] },
  host: { title: 'Host and folders', intro: 'Workstation · Online', fields: [['Allowed roots', '/home/you/work'], ['Default folder', '/home/you/work/website']] },
  tasks: { title: 'Task / room templates', intro: 'Reusable teams for new tasks.', fields: [['Template name', 'pair'], ['Agents', 'Developer + Critic'], ['Briefing', 'Work together and provide verification evidence']] },
};
export function SettingsPage({ editor, go, notify }: { editor?: string; go: (p: Page) => void; notify: (s: string) => void }) {
  const [values, setValues] = useState<Record<string, string>>({});
  const d = editor && definitions[editor];
  return <main className="fleet-form-page"><PageHeader title={d ? d.title : 'Configuration'} subtitle={d ? d.intro : 'Reusable defaults for simple session creation'} onBack={() => go(editor ? { kind: 'settings' } : { kind: 'home' })} />{d ? <form onSubmit={e => { e.preventDefault(); notify('Definition saved in this preview'); }}>{d.fields.map(([label, value]) => <Field key={`${editor}-${label}`} label={label}>{['Purpose', 'Instructions', 'Context / briefing', 'Briefing'].includes(label) ? <textarea required value={values[`${editor}-${label}`] ?? value} onChange={e => setValues(v => ({ ...v, [`${editor}-${label}`]: e.target.value }))} /> : <input required readOnly={label === 'Credentials'} value={values[`${editor}-${label}`] ?? value} onChange={e => setValues(v => ({ ...v, [`${editor}-${label}`]: e.target.value }))} />}</Field>)}<Row title="Used by" subtitle="Current sessions keep their saved snapshots" /><Button primary type="submit">Save {editor === 'permissions' ? 'permission profile' : editor}</Button></form> : <>{[['template', 'Agent Templates', 'Developer, Tester, Writer · Combine role, brain and permissions'], ['role', 'Roles', 'Purpose, instructions and responsibilities'], ['brain', 'Brains', 'Harness, model and runtime settings'], ['permissions', 'Permission profiles', 'Read-only, Workspace edits, Restricted'], ['host', 'Host and folders', 'Workstation · Allowed roots and default folder'], ['tasks', 'Task / room templates', 'single · pair · team · custom']].map(([key, title, subtitle]) => <Row key={key} title={title} subtitle={subtitle} onClick={() => go({ kind: 'settings', editor: key })} />)}<Button onClick={() => notify('Something went wrong. Please try again.')}>Preview notification</Button></>}</main>;
}
export function AccountPage({ step, go, notify, onComplete }: { step: string; go: (p: Page) => void; notify: (s: string) => void; onComplete: (name: string) => void }) {
  const [email, setEmail] = useState('you@example.com');
  const [name, setName] = useState('Vitalii');
  const next = (step: string) => go({ kind: 'account', step });
  if(step === 'welcome') return <Onboarding onComplete={() => onComplete(name.trim() || 'there')} />;
  return <main className="fleet-account fleet-form-page"><h2 className="fleet-brand">ours</h2>{step === 'confirm' ? <><h1>Check your email</h1><p>We sent a confirmation link to {email}</p><Button onClick={() => next('signup')}>Use a different email</Button><p>Open the link to confirm your email and finish setting up your account.</p><p>Waiting for email confirmation</p><Button primary onClick={() => next('welcome')}>Preview confirmed email</Button><Button onClick={() => notify('Confirmation email resent in preview')}>Resend email</Button><Button onClick={() => next('login')}>Back to log in</Button></> : <form onSubmit={e => { e.preventDefault(); next(step === 'signup' ? 'confirm' : 'welcome'); }}><h1>{step === 'signup' ? 'Create account' : 'Log in'}</h1><p>{step === 'signup' ? 'One account for your connected identities.' : 'Welcome back. Sign in to your account.'}</p><p className="muted">Mock account — use example details. Nothing is sent.</p>{step === 'signup' && <Field label="Your name"><input required value={name} onChange={e => setName(e.target.value)} autoComplete="off" /></Field>}<Field label="Email"><input type="email" required value={email} onChange={e => setEmail(e.target.value)} /></Field><Field label="Password"><input type="password" required minLength={8} defaultValue="preview-password" autoComplete={step === 'signup' ? 'new-password' : 'current-password'} /></Field>{step === 'signup' && <label className="fleet-check"><input type="checkbox" required /> I accept the Terms of Use and Privacy Policy.</label>}<Button primary type="submit">{step === 'signup' ? 'Create account' : 'Log in'}</Button><Button onClick={() => next(step === 'signup' ? 'login' : 'signup')}>{step === 'signup' ? 'Already have an account? Log in' : 'Create an account'}</Button></form>}</main>;
}
