import {useLayoutEffect,useRef,type ReactNode} from 'react';
import {animate,motion,useMotionValue,useReducedMotion} from 'framer-motion';
export function SegmentedSwitch({label,options,value,onChange}:{label:string;options:{id:string;label:string;badge?:ReactNode}[];value:string;onChange:(id:string)=>void}){
 const ref=useRef<HTMLDivElement>(null),x=useMotionValue(0),reduce=useReducedMotion();const selected=useRef(value);selected.current=value;
 const animation=useRef<ReturnType<typeof animate>>();const gesture=useRef({id:-1,x:0,y:0,start:0,active:false,samples:[] as {x:number,t:number}[]});const suppress=useRef(false);
 const step=()=>((ref.current?.clientWidth??8)-8)/options.length;
 const settle=(id:string,velocity=0)=>{animation.current?.stop();const to=options.findIndex(o=>o.id===id)*step();if(reduce)x.set(to);else animation.current=animate(x,to,{type:'spring',stiffness:400,damping:40,velocity});};
 useLayoutEffect(()=>{settle(value);},[value,reduce]);
 useLayoutEffect(()=>{if(!ref.current)return;const observer=new ResizeObserver(()=>{animation.current?.stop();x.set(options.findIndex(o=>o.id===selected.current)*step());});observer.observe(ref.current);return()=>{observer.disconnect();animation.current?.stop();};},[]);
 const finish=(id:number,commit:boolean)=>{const g=gesture.current,el=ref.current;if(g.id!==id||!el)return;let next=value,velocity=0;if(commit&&g.active){const a=g.samples[0],b=g.samples.at(-1);if(a&&b&&b.t>a.t&&performance.now()-b.t<100)velocity=(b.x-a.x)*1000/(b.t-a.t);const projected=x.get()+velocity/1000*.99/(1-.99);next=options[Math.max(0,Math.min(options.length-1,Math.round(projected/step())))].id;suppress.current=true;setTimeout(()=>{suppress.current=false;},0);}gesture.current={id:-1,x:0,y:0,start:0,active:false,samples:[]};if(el.hasPointerCapture(id))el.releasePointerCapture(id);settle(next,velocity);if(next!==value)onChange(next);};
 return <div ref={ref} className="conversation-list-modes shared-segmented-switch" role="tablist" aria-label={label} onPointerDown={e=>{if(e.isPrimary){animation.current?.stop();gesture.current={id:e.pointerId,x:e.clientX,y:e.clientY,start:x.get(),active:false,samples:[{x:e.clientX,t:performance.now()}]};}}} onPointerMove={e=>{const g=gesture.current;if(g.id!==e.pointerId)return;const dx=e.clientX-g.x,dy=e.clientY-g.y;if(!g.active){if(Math.abs(dx)<10&&Math.abs(dy)<10)return;if(Math.abs(dy)>Math.abs(dx)){finish(e.pointerId,false);return;}animation.current?.stop();g.active=true;e.currentTarget.setPointerCapture(e.pointerId);}e.preventDefault();x.set(Math.max(0,Math.min(step()*(options.length-1),g.start+dx)));const now=performance.now();g.samples=[...g.samples.filter(s=>now-s.t<100),{x:e.clientX,t:now}];}} onPointerUp={e=>finish(e.pointerId,true)} onPointerCancel={e=>finish(e.pointerId,false)} onLostPointerCapture={e=>finish(e.pointerId,false)}>
 <motion.span aria-hidden className="shared-segmented-thumb" style={{x,width:`calc((100% - 8px) / ${options.length})`}}/>
 {options.map((o,index)=><button key={o.id} type="button" role="tab" aria-selected={value===o.id} tabIndex={value===o.id?0:-1} onClick={()=>{if(!suppress.current)onChange(o.id);}} onKeyDown={e=>{if(!['ArrowLeft','ArrowRight','Home','End'].includes(e.key))return;e.preventDefault();const next=e.key==='Home'?0:e.key==='End'?options.length-1:(index+(e.key==='ArrowRight'?1:-1)+options.length)%options.length;onChange(options[next].id);(ref.current?.querySelectorAll('button')[next])?.focus();}}>{o.label}{o.badge}</button>)}
 </div>;
}
