import assert from 'node:assert/strict';
import { chromium, expect } from '@playwright/test';
import { createFleetPreviewServer } from '../scripts/fleet-preview-server.mjs';
const server = createFleetPreviewServer();
await new Promise(r => server.listen(0, '127.0.0.1', r));
const origin = `http://127.0.0.1:${server.address().port}`;
const browser = await chromium.launch();
try {
  for(const width of [390, 1280]) {
    const page = await browser.newPage({ viewport: { width, height: 844 } });
    const errors = []; page.on('pageerror', e => errors.push(e.message));
    const tab = name => page.getByRole('tab', { name, exact: true });
    const button = name => page.getByRole('button', { name, exact: true });
    const list = page.locator('.fleet-list');
    const composer = page.locator('.fleet-chat-slot:not([hidden]) .composer textarea');
    await page.goto(origin + '/fleet');
    await expect(tab('All')).toHaveAttribute('aria-selected','true');
    await expect(list).toContainText('Maya'); await expect(list).toContainText('Coordinator'); await expect(list).toContainText('Launch website');
    await tab('Workspace').click(); await page.getByRole('combobox', { name: 'Workspace conversations' }).selectOption('Agents'); await page.getByRole('combobox', { name: 'Agent lifetime' }).selectOption('Temporary');
    await expect(list).toContainText('Developer'); await expect(list).toContainText('Writer'); await expect(list).not.toContainText('Coordinator');
    await page.getByRole('combobox', { name: 'Agent lifetime' }).selectOption('Persistent'); await expect(list).toContainText('Coordinator'); await expect(list).not.toContainText('Writer');
    await page.getByRole('combobox', { name: 'Workspace conversations' }).selectOption('Tasks'); await page.getByLabel('Search chats',{exact:true}).fill('Launch');
    await list.getByRole('button', {name:/^Launch website Task/}).click();
    await expect(list.getByRole('heading')).toHaveText('Launch website');
    await expect(tab('All')).toHaveCount(0); await expect(list.getByRole('button',{name:/^Maya/})).toHaveCount(0); await expect(list).not.toContainText('Research assistant');
    await expect(page.getByLabel('Search this task',{exact:true})).toHaveValue('');
    await page.goBack(); await expect(page.getByRole('combobox', { name: 'Workspace conversations' })).toHaveValue('Tasks');
    await page.goForward(); await expect(list.getByRole('heading')).toHaveText('Launch website');
    await list.getByRole('button', {name:/^Developer Direct/}).click(); await composer.fill('Keep this draft');
    if(width<861) await button('Back to conversations').click();
    await list.getByRole('button',{name:/^Room Shared/}).click();
    if(width<861) await button('Back to conversations').click();
    await list.getByRole('button',{name:/^Developer Direct/}).click(); await expect(composer).toHaveValue('Keep this draft');
    if(width<861) await button('Back to conversations').click();
    await page.screenshot({path:`/tmp/chats-task-${width}.png`});
    await page.reload(); await expect(list.getByRole('heading')).toHaveText('Launch website');
    await button('‹ Back to chats').click(); await expect(page.getByRole('combobox', { name: 'Workspace conversations' })).toHaveValue('Tasks'); await expect(page.getByLabel('Search chats',{exact:true})).toHaveValue('Launch');
    await page.getByLabel('Search chats',{exact:true}).fill(''); await tab('External').click();
    await expect(list).toContainText('Maya'); await expect(list).not.toContainText('Coordinator');
    await page.getByRole('group',{name:'Decide whether to accept Noor'}).getByRole('button',{name:'Approve',exact:true}).click();
    await expect(list.getByRole('button',{name:/^Noor/})).toBeVisible();
    await list.getByRole('button',{name:/^Maya/}).click(); await composer.fill('External draft');
    if(width<861) await button('Back to conversations').click();
    await button('Navigate').click(); const dialog = page.getByRole('dialog');
    await expect(dialog.locator('.fleet-destination')).toHaveCount(2); await dialog.getByRole('button',{name:/^Tasks/}).click();
    await expect(page.getByRole('heading',{name:'Tasks',exact:true})).toBeVisible();
    await button('Navigate').click(); await page.getByRole('dialog').getByRole('button',{name:/^Chats/}).click();
    await expect(tab('External')).toHaveAttribute('aria-selected','true');
    await list.getByRole('button',{name:/^Maya/}).click(); await expect(composer).toHaveValue('External draft');
    if(width<861) await button('Back to conversations').click();
    await button('Add or connect').click(); for(const name of ['New chat','New persistent agent','New task','Generate invite','Accept invite']) await expect(button(name)).toBeVisible();
    await button('New chat').click(); await expect(composer).toBeVisible(); await composer.fill('Draft new chat');
    if(width<861) await button('Back to conversations').click(); else await button('Close conversation').click();
    await button('Add or connect').click(); await button('New chat').click(); await expect(composer).toHaveValue('Draft new chat');
    if(width<861) await button('Back to conversations').click();
    await page.screenshot({path:`/tmp/chats-filters-${width}.png`});
    assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
    assert.deepEqual(errors,[]); await page.close();
    console.log(`${width}px: unified filters, task focus, routing, drafts, existing creation menu PASS`);
  }
} finally { await browser.close(); await new Promise(r=>server.close(r)); }
