import assert from 'node:assert/strict';
import { agentPreview, externalPreview } from '../src/fleet/chat-previews';
const event=(kind:string,payload:any,extra:any={})=>({kind,payload,eventId:kind,at:'2026-09-28T07:00:00Z',...extra});
const prompt=event('prompt.admitted',{text:{text:'internal'},displayText:{text:'Hello there'}},{source:'owner_admin_console',promptId:'p'});
const chunk=(text:string,extra:any={})=>event('message.chunk',{role:'assistant',content:{type:'text',text,...extra}},{messageId:'m',at:'2026-09-28T07:01:00Z'});
assert.equal(agentPreview([]).text,'No messages yet');
assert.equal(agentPreview([prompt]).text,'You: Hello there');
assert.equal(agentPreview([prompt,chunk('RE'),chunk('ADY')]).text,'Incoming: READY');
assert.equal(agentPreview([prompt,chunk('secret'),chunk('',{redacted:true})]).text,'You: Hello there');
assert.equal(agentPreview([event('prompt.admitted',{text:{text:'boot'}},{source:'startup',promptId:'boot'})]).text,'No messages yet');
assert.equal(agentPreview([prompt,event('tool.upsert',{toolCallId:'tool',title:'Internal tool',rawOutput:{json:{secret:'internal'}}})]).text,'You: Hello there');
const page=(dir:string,text:string,kind='text',preview?:string)=>({messages:[{dir,text,message_kind:kind,date:'2026-09-28T07:00:00Z'}],preview} as any);
assert.equal(externalPreview(page('out','Hello\nthere'),'Contact').text,'You: Hello there');
assert.equal(externalPreview(page('in','Response'),'Contact').text,'Incoming: Response');
assert.equal(externalPreview(page('in','','file'),'Contact').text,'Incoming: File attachment');
assert.equal(externalPreview(page('out','','file'),'Contact').text,'You: File attachment');
assert.equal(externalPreview({messages:[]} as any,'Contact').text,'No messages yet');
assert.equal(externalPreview(page('in','unprojected','text','Alice · Hello room'),'ours-cowork:Room').text,'Incoming: Alice · Hello room');
assert.ok(externalPreview(page('in','a'.repeat(400)),'Contact').text.length<320);
console.log('Chat previews: direction, stream assembly, redaction, no tool/startup content, empty/files/room projection PASS');
